(* tokens.mly — token 类型的单一事实来源（决策 007）。
   menhir --only-tokens 只生成 Tokens 模块（类型定义，无分析器代码）；
   将来的语法文件用 --external-tokens Tokens 导入，不要再声明一遍。
   引号里的是 token 别名，将来写文法可直接用拼写。 *)

(* ---- C17 关键字（44 个，决策 005；C17 词法 ≡ C11） ---- *)
%token AUTO "auto"
%token BREAK "break"
%token CASE "case"
%token CHAR "char"
%token CONST "const"
%token CONTINUE "continue"
%token DEFAULT "default"
%token DO "do"
%token DOUBLE "double"
%token ELSE "else"
%token ENUM "enum"
%token EXTERN "extern"
%token FLOAT "float"
%token FOR "for"
%token GOTO "goto"
%token IF "if"
%token INLINE "inline"
%token INT "int"
%token LONG "long"
%token REGISTER "register"
%token RESTRICT "restrict"
%token RETURN "return"
%token SHORT "short"
%token SIGNED "signed"
%token SIZEOF "sizeof"
%token STATIC "static"
%token STRUCT "struct"
%token SWITCH "switch"
%token TYPEDEF "typedef"
%token UNION "union"
%token UNSIGNED "unsigned"
%token VOID "void"
%token VOLATILE "volatile"
%token WHILE "while"
%token ALIGNAS "_Alignas"
%token ALIGNOF "_Alignof"
%token ATOMIC "_Atomic"
%token BOOL "_Bool"
%token COMPLEX "_Complex"
%token GENERIC "_Generic"
%token IMAGINARY "_Imaginary"
%token NORETURN "_Noreturn"
%token STATIC_ASSERT "_Static_assert"
%token THREAD_LOCAL "_Thread_local"

(* ---- 标点（C17 §6.4.6；双字符组归一化到同一 token，不单设） ---- *)
%token LBRACKET "["
%token RBRACKET "]"
%token LPAREN "("
%token RPAREN ")"
%token LBRACE "{"
%token RBRACE "}"
%token DOT "."
%token ARROW "->"
%token INC "++"
%token DEC "--"
%token AMP "&"
%token STAR "*"
%token PLUS "+"
%token MINUS "-"
%token TILDE "~"
%token BANG "!"
%token SLASH "/"
%token PERCENT "%"
%token LSHIFT "<<"
%token RSHIFT ">>"
%token LT "<"
%token GT ">"
%token LE "<="
%token GE ">="
%token EQEQ "=="
%token NEQ "!="
%token CARET "^"
%token PIPE "|"
%token ANDAND "&&"
%token OROR "||"
%token QUESTION "?"
%token COLON ":"
%token SEMI ";"
%token ELLIPSIS "..."
%token ASSIGN "="
%token STAR_ASSIGN "*="
%token SLASH_ASSIGN "/="
%token PERCENT_ASSIGN "%="
%token PLUS_ASSIGN "+="
%token MINUS_ASSIGN "-="
%token LSHIFT_ASSIGN "<<="
%token RSHIFT_ASSIGN ">>="
%token AMP_ASSIGN "&="
%token CARET_ASSIGN "^="
%token PIPE_ASSIGN "|="
%token COMMA ","

(* ---- 字面量与标识符：payload = 原始拼写（决策 007） ---- *)
%token <string> IDENT
%token <string> INT_LIT
%token <string> FLOAT_LIT
%token <string> CHAR_LIT
%token <string> STRING_LIT
%token EOF

%%
